export const MockAnime = {
  mal_id: 1,
  url: "https://myanimelist.net/anime/1",
  images: {
    jpg: { image_url: "/image-placeholder.svg" },
    webp: { image_url: "/image-placeholder.svg" }
  },
  trailer: { youtube_id: '9bZkp7q19f0', url: 'https://www.youtube.com/watch?v=9bZkp7q19f0', embed_url: "https://www.youtube.com/embed/9bZkp7q19f0" },
  approved: true,
  titles: [],
  title: "Naruto",
  title_english: "Naruto",
  title_japanese: "ナルト",
  title_synonyms: [],
  type: "TV",
  source: "Manga",
  episodes: 220,
  status: "Finished Airing",
  airing: false,
  aired: {},
  duration: "23 min per ep",
  rating: "PG-13",
  score: 8.3,
  scored_by: 1000000,
  rank: 100,
  popularity: 200,
  members: 2000000,
  favorites: 100000,
  synopsis: "A story about a young ninja...A story about a young ninja...A story about a young ninja...",
  background: "",
  season: "Fall",
  year: 2002,
  broadcast: {},
  producers: [],
  licensors: [],
  studios: [],
  genres: [
    { mal_id: 1, name: "Action" },
    { mal_id: 2, name: "Adventure" }
  ],
  explicit_genres: [],
  themes: [],
  demographics: []
};